# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='twitter.proto',
  package='lab1',
  serialized_pb='\n\rtwitter.proto\x12\x04lab1\"\xfe\x04\n\x05Tweet\x12\x11\n\tis_delete\x18\x01 \x02(\x08\x12\"\n\x06\x64\x65lete\x18\x02 \x01(\x0b\x32\x12.lab1.Tweet.Delete\x12\"\n\x06insert\x18\x03 \x01(\x0b\x32\x12.lab1.Tweet.Insert\x1a!\n\x05\x43oord\x12\x0b\n\x03lat\x18\x01 \x02(\x02\x12\x0b\n\x03lon\x18\x02 \x02(\x02\x1a\x92\x01\n\x05Place\x12\x0b\n\x03url\x18\x01 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x02(\t\x12\x14\n\x0c\x63ountry_code\x18\x03 \x02(\t\x12\x12\n\nplace_type\x18\x04 \x02(\t\x12\'\n\x0c\x62ounding_box\x18\x05 \x03(\x0b\x32\x11.lab1.Tweet.Coord\x12\n\n\x02id\x18\x06 \x02(\t\x12\x0c\n\x04name\x18\x07 \x02(\t\x1a!\n\x06\x44\x65lete\x12\x0b\n\x03uid\x18\x01 \x02(\x05\x12\n\n\x02id\x18\x02 \x02(\x03\x1a\xbe\x02\n\x06Insert\x12\x11\n\ttruncated\x18\x01 \x02(\x08\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08reply_to\x18\x03 \x01(\x03\x12\x15\n\rreply_to_name\x18\x04 \x01(\t\x12\n\n\x02id\x18\x05 \x02(\x03\x12\x0b\n\x03uid\x18\x06 \x02(\x03\x12\x16\n\x0e\x66\x61vorite_count\x18\x07 \x01(\x05\x12\x0e\n\x06source\x18\x08 \x01(\t\x12\x11\n\tretweeted\x18\t \x02(\x08\x12\x1a\n\x12possibly_sensitive\x18\n \x01(\x08\x12\x0c\n\x04lang\x18\x0b \x01(\t\x12\x12\n\ncreated_at\x18\x0c \x02(\t\x12 \n\x05\x63oord\x18\r \x01(\x0b\x32\x11.lab1.Tweet.Coord\x12\x14\n\x0c\x66ilter_level\x18\x0e \x02(\t\x12 \n\x05place\x18\x0f \x01(\x0b\x32\x11.lab1.Tweet.Place\"%\n\x06Tweets\x12\x1b\n\x06tweets\x18\x01 \x03(\x0b\x32\x0b.lab1.Tweet')




_TWEET_COORD = descriptor.Descriptor(
  name='Coord',
  full_name='lab1.Tweet.Coord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='lat', full_name='lab1.Tweet.Coord.lat', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lon', full_name='lab1.Tweet.Coord.lon', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=124,
  serialized_end=157,
)

_TWEET_PLACE = descriptor.Descriptor(
  name='Place',
  full_name='lab1.Tweet.Place',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='url', full_name='lab1.Tweet.Place.url', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='country', full_name='lab1.Tweet.Place.country', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='country_code', full_name='lab1.Tweet.Place.country_code', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='place_type', full_name='lab1.Tweet.Place.place_type', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bounding_box', full_name='lab1.Tweet.Place.bounding_box', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='lab1.Tweet.Place.id', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='lab1.Tweet.Place.name', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=160,
  serialized_end=306,
)

_TWEET_DELETE = descriptor.Descriptor(
  name='Delete',
  full_name='lab1.Tweet.Delete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uid', full_name='lab1.Tweet.Delete.uid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='lab1.Tweet.Delete.id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=308,
  serialized_end=341,
)

_TWEET_INSERT = descriptor.Descriptor(
  name='Insert',
  full_name='lab1.Tweet.Insert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='truncated', full_name='lab1.Tweet.Insert.truncated', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='lab1.Tweet.Insert.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reply_to', full_name='lab1.Tweet.Insert.reply_to', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reply_to_name', full_name='lab1.Tweet.Insert.reply_to_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='lab1.Tweet.Insert.id', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uid', full_name='lab1.Tweet.Insert.uid', index=5,
      number=6, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='favorite_count', full_name='lab1.Tweet.Insert.favorite_count', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='source', full_name='lab1.Tweet.Insert.source', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='retweeted', full_name='lab1.Tweet.Insert.retweeted', index=8,
      number=9, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='possibly_sensitive', full_name='lab1.Tweet.Insert.possibly_sensitive', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lang', full_name='lab1.Tweet.Insert.lang', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='created_at', full_name='lab1.Tweet.Insert.created_at', index=11,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='coord', full_name='lab1.Tweet.Insert.coord', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filter_level', full_name='lab1.Tweet.Insert.filter_level', index=13,
      number=14, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='place', full_name='lab1.Tweet.Insert.place', index=14,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=344,
  serialized_end=662,
)

_TWEET = descriptor.Descriptor(
  name='Tweet',
  full_name='lab1.Tweet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='is_delete', full_name='lab1.Tweet.is_delete', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delete', full_name='lab1.Tweet.delete', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='insert', full_name='lab1.Tweet.insert', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TWEET_COORD, _TWEET_PLACE, _TWEET_DELETE, _TWEET_INSERT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=662,
)


_TWEETS = descriptor.Descriptor(
  name='Tweets',
  full_name='lab1.Tweets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tweets', full_name='lab1.Tweets.tweets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=664,
  serialized_end=701,
)

_TWEET_COORD.containing_type = _TWEET;
_TWEET_PLACE.fields_by_name['bounding_box'].message_type = _TWEET_COORD
_TWEET_PLACE.containing_type = _TWEET;
_TWEET_DELETE.containing_type = _TWEET;
_TWEET_INSERT.fields_by_name['coord'].message_type = _TWEET_COORD
_TWEET_INSERT.fields_by_name['place'].message_type = _TWEET_PLACE
_TWEET_INSERT.containing_type = _TWEET;
_TWEET.fields_by_name['delete'].message_type = _TWEET_DELETE
_TWEET.fields_by_name['insert'].message_type = _TWEET_INSERT
_TWEETS.fields_by_name['tweets'].message_type = _TWEET
DESCRIPTOR.message_types_by_name['Tweet'] = _TWEET
DESCRIPTOR.message_types_by_name['Tweets'] = _TWEETS

class Tweet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Coord(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TWEET_COORD
    
    # @@protoc_insertion_point(class_scope:lab1.Tweet.Coord)
  
  class Place(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TWEET_PLACE
    
    # @@protoc_insertion_point(class_scope:lab1.Tweet.Place)
  
  class Delete(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TWEET_DELETE
    
    # @@protoc_insertion_point(class_scope:lab1.Tweet.Delete)
  
  class Insert(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TWEET_INSERT
    
    # @@protoc_insertion_point(class_scope:lab1.Tweet.Insert)
  DESCRIPTOR = _TWEET
  
  # @@protoc_insertion_point(class_scope:lab1.Tweet)

class Tweets(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TWEETS
  
  # @@protoc_insertion_point(class_scope:lab1.Tweets)

# @@protoc_insertion_point(module_scope)
